name: cda_online_skf

on:
  schedule:
    - cron: '0 6 * * *'  # Todo dia às 03:00 no Brasil (UTC-3)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          SKF_CREDENTIALS: ${{ secrets.SKF_CREDENTIALS }}
          SKF_BASE: ${{ secrets.SKF_BASE }}
        run: |
          python cda_online_skf.py
